name: Release @vueup/vue-quill

on: 
  push: 
    branches: 
      - alpha
      - beta
      - master
    paths: 
      - 'packages/vue-quill/**'
jobs: 
  release: 
    name: Build and release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - name: Install root deps
        run: npm ci
      - name: Install package deps
        working-directory: packages/vue-quill
        run: npm ci
      - name: Release package
        working-directory: packages/vue-quill
        # run: npx ts-node ../../scripts/release.ts vue-quill
        run: npx semantic-release
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}